### ISSUE TITLE
Title tag not changing 

### ISSUE THREAD

**Issue by awfulminded** [solidjs/solid-meta#18]
Maybe I don’t understand something, but I can’t change the title tag at all.
I even copied the 1in1 code from the repository + created an empty project, anyway, the title and other tags do not changeю
javscript not throwing any errors.
Maybe it has something to do with solid-router because they have at least one common ```<Link>``` tag, but I could be wrong. Doesn't work without ```<Router>``` either.

```
import type { Component } from 'solid-js';
import { Meta, MetaProvider, Title } from '@solidjs/meta';

const App: Component = () => (
  <MetaProvider>
    <div class="Home">
      <Title>Title of page</Title>
      <Meta name="example" content="whatever" />
      // ...
    </div>
  </MetaProvider>
);

export default App;
```

```
import { render } from 'solid-js/web';

import App from './App';
import { Router } from '@solidjs/router';

render(() => <Router><App /></Router>, document.getElementById('root') as HTMLElement);
```

**Comment by outbackStack** [comment]
would you be able to put this in codesandbox.io or something similar so we could see what the issues are?

**Comment by AlexNolasco** [comment]
I had similar issue while testing the lib with just a title. I removed the hard coded title from the html then it worked.

**Comment by solution-loisir** [comment]
I think that the hard coded title should serve as a fallback (no is required). Is there a way to make meta work without removing the title from the html?

**Comment by botanegg** [comment]
Was it broken between `0.27.5` and `0.28.0` again?

**Comment by ryansolid** [comment]
We never removed or commandeered the title tag if it didn't have a data-sm attribute. 0.28.0 removed the ability to have an existing title tag at all, but that should have been fixed in 0.28.2.

The solution as it was in 0.27.5 is to add an empty data-sm attribute to it.

**Comment by botanegg** [comment]
@ryansolid thank you for fast answer

Sorry i run on outdated solid-meta `0.28.1`  
Problem solved after move to `@solidjs/meta`  and latest version

**Comment by boombang** [comment]
@ryansolid @botanegg the issue is still reproducible on `0.28.2`

**Comment by e23thr** [comment]
@boombang I just fix this by remove <title> tag from index.html file

**Comment by extracold1209** [comment]
In my opinion, not only should the title in the MetaProvider be cascaded, but the title already in index.html should also be overwritten.

This is because there is already a rule that only the ‘last created one’ is applied to the titles in the MetaProvider.

**Comment by EricRovell** [comment]
Have the same issue. Removing tags from html file is not an option, I am using SPA and I would lose link previews when sharing the link. The problem solved by adding empty `data-sm` attribute to existing tags.

**Comment by Worble** [comment]
Just ran into this as well, I think it would be a massive help if the docs mentioned somewhere that adding the `data-sm` attribute into your original html title would fix this issue if there's no plan to otherwise change this functionality. 

I'm using Solid purely client side and there's a lot of good reasons to keep a title in the base html even if your SPA will later override it.

**Comment by GriffinJohnston** [comment]
I think the existing behavior is fine, it just needs to be documented. Just created a PR to add a note to the installation section of the docs.
